Docker/ubuntu22.04.Dockerfile
deepprep/deepprep.sh
deepprep/nextflow/bin/gpu_schedule_lock.py
deepprep/nextflow/bin/gpu_schedule_run.py
deepprep/nextflow/deepprep.common.config
deepprep/nextflow/deepprep.nf

CHG: change single to double
CHG: change GPU info checking from lock to run
CHG: container can be str or file_path
NEW: add FREESURFER env

NEW: run with docker

---

docs/source/outputs.rst
docs/source/processing.rst

CHG: update processing.rst outputs.rst

CHG: update processing.rst outputs.rst

---

docs/source/usage_cluster.rst

CHG: update AWS process

---

docs/source/links.rst

CHG: update the link of test sample and sif

CHG: update the link of test sample and sif

---

Docker/README.md
deepprep/deepprep.sh
deepprep/nextflow/bin/input_bids_validator.py
deepprep/nextflow/deepprep.nf

change the process memory usage

CHG: change the process memory usage

---

deepprep/nextflow/bin/anat_get_t1w_file_in_bids.py
deepprep/nextflow/bin/bold_get_bold_file_in_bids.py

#104 
Flexibility to modify input subject_ids

DEBUG:Flexibility to modify input subject_ids

---

deepprep/nextflow/deepprep.nf

#102 
1. Fixed the memory setting with 'anat_get_t1w_file_in_bids' and 'anat_get_t1w_file_in_bids' and anat_motioncor.
2. Fixed the connect error with 'deepprep_init'

FIX: the memory setting with same processes

---

deepprep/SynthMorph/mri_bold_apply_synthmorph.py
deepprep/nextflow/bin/apply_trans_matrix_from_t1_to_MNI.py

NEW:Added Bold/anat separately run script that applies transformation matrix from T1w space to standard space

NEW:Added Bold/anat separate script to apply transformation matrix

---

deepprep/nextflow/deepprep.common.config

CHG: change model path

---

Docker/ubuntu22.04.Dockerfile
deepprep/nextflow/bin/bold_confounds_combine.py

DEBUG: fixed the confounds_conbine

DEBUG: fixed the confounds_conbine

---

deepprep/nextflow/bin/bold_confounds_combine.py

DEBUG: fixed the bold_confounds process

 DEBUG: fixed the bold_confounds process

---

deepprep/nextflow/bin/bold_apply_transform_chain.py
deepprep/nextflow/bin/bold_confounds_part2.py

sub-*_ses-*_task-rest_space-MNI152NLin6Asym_res-02_desc-preproc_bold.json

CHG: add corresponding .json file

---

deepprep/nextflow/bin/bold_apply_transform_chain.py
deepprep/nextflow/bin/bold_averagesingnal.py
deepprep/nextflow/bin/bold_concat.py
deepprep/nextflow/bin/bold_confounds_combine.py
deepprep/nextflow/bin/bold_confounds_part1.py
deepprep/nextflow/bin/bold_confounds_part2.py
deepprep/nextflow/bin/bold_preprocess.py
deepprep/nextflow/bin/bold_upsampled.py
deepprep/nextflow/bin/qc_bold_to_space.py
deepprep/nextflow/bin/qc_bold_tsnr.py
deepprep/nextflow/deepprep.nf

CHG: reduce the time of reading bids dataset

CHG: reduce the time of reading bids dataset

---

deepprep/nextflow/bin/qc_create_report.py
deepprep/nextflow/bin/reports/core.py

FIX: subject_id must be 01 02 etc

FIX: subject_id must be 01 02 etc

---

docs/source/changes.rst
docs/source/usage_cluster.rst

CHG: change the download url

---

Docker/README.md
Docker/singularity_ubuntu22.04.def
Docker/ubuntu22.04.Dockerfile

NEW: add Docker 24.1.0

---

deepprep/deepprep.sh
deepprep/nextflow/deepprep.common.config
deepprep/nextflow/deepprep.nf

change cpu require

---

Docker/README.md
Docker/ubuntu22.04.Dockerfile
README.rst
deepprep/nextflow/deepprep.common.config
docs/source/installation.rst
docs/source/outputs.rst
docs/source/usage_cluster.rst
docs/source/usage_local.rst

VERSION: create branch 24.1.1

---

deepprep/SUGAR/predict.py

FIX: SUGAR在无GPU环境中使用device=auto发生错误

FIX: SUGAR在无GPU环境中使用device=auto发生错误

---

Docker/README.md
Docker/singularity_ubuntu22.04.def
Docker/ubuntu22.04.Dockerfile
deepprep/SUGAR/predict.py
deepprep/nextflow/deepprep.nf
docs/source/usage_cluster.rst
docs/source/usage_local.rst

DOC: 添加首次使用Singularity执行DeepPrep时，必须下载nextflow的依赖
NEW: for a2009s label
CHG: support singularity build

support singularity build

---

docs/source/links.rst
docs/source/usage_local.rst

CHG: change the link of test sample file
CHG: fixed the example for Docker local

CHG: change the link of test sample file

---

README.rst
docs/source/usage_local.rst

CHG: changed method of getting the deps of nextflow to sync
CHG: changed the file type of figure to png

CHG: changed method of getting the deps of nextflow to sync

---

README.rst

FIX: figure link error

---

README.rst

CHG: changed method of getting the deps of nextflow to sync
CHG: changed the file type of figure to png

CHG: changed the file type of figure to png

---

docs/source/processing.rst

DOC: fixed same works

---

docs/source/outputs.rst

Cifti docs outputs

---

Docker/ubuntu22.04.Dockerfile
deepprep/qc/qc.nf
deepprep/web/pages/3_📝Quick QC.py

QuickQC path error

---

README.rst
deepprep/web/pages/3_📝Quick QC.py
docs/source/usage_GUI.rst

CHG: updated figures
